# Generated by Django 3.2.1 on 2021-06-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_count', models.PositiveIntegerField(default=0)),
                ('authors_count', models.PositiveIntegerField(default=0)),
                ('read_number_avg', models.PositiveIntegerField(default=0)),
                ('read_number_max', models.PositiveIntegerField(default=0)),
                ('read_number_min', models.PositiveIntegerField(default=0)),
                ('read_number_sum', models.PositiveIntegerField(default=0)),
                ('highest_read_title', models.TextField(default='-')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
