# Generated by Django 3.2.1 on 2021-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystats',
            name='highest_read_title',
            field=models.TextField(default='-'),
        ),
    ]
