# Generated by Django 3.2.1 on 2021-05-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dailystats_highest_read_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
