# Generated by Django 3.2.1 on 2021-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dailystats_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystats',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
