# Generated by Django 3.2.1 on 2021-05-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_number',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='stars_number',
        ),
    ]
