# Generated by Django 3.2.1 on 2021-05-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210521_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcounts',
            name='blog_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
