# Generated by Django 3.2.1 on 2021-06-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_img',
            field=models.ImageField(blank=True, default='istockphoto-default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
