# Generated by Django 3.2.1 on 2021-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_img',
            field=models.ImageField(blank=True, default='default_cover_img.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
